app/models/certificate.py
from datetime import datetime
from typing import List, Optional

from models.base_model import BaseModel
from models.dns_config import DNSConfig
#from models.domain import Domain
#from models.cloudflare import CloudflareConfig

class Certificate(BaseModel):
    model_name = "certificates"  # Define the model name
    schema = {
        **BaseModel.schema,
        'name': {'type': str, 'required': True},
        'email': {'type': str, 'required': True},
        'domains': {'type': (list, str), 'required': True},
        'dns_challenge': {'type': bool, 'required': True},
        'dns_config': {'type': (DNSConfig, type(None)), 'required': False},
        'certificate_path': {'type': (str, type(None)), 'required': False},
        'private_key_path': {'type': (str, type(None)), 'required': False}
    }

    def __init__(self, **kwargs):
        """
        Initialize the Certificate model, calling the parent constructor.
        """
        super().__init__(**kwargs)
        
    def get_domain_names(self) -> List[str]:
        return [domain.name if isinstance(domain, BaseModel) else domain for domain in self.domains]

    def get_email(self) -> str:
        return self.email

    def set_email(self, email: str):
        self.email = email
        self.updated_at = datetime.utcnow()

    def get_name(self) -> str:
        return self.name

    def set_name(self, name: str):
        self.name = name
        self.updated_at = datetime.utcnow()

    def get_domains(self) -> List[object]:
        return self.domains

    def set_domains(self, domains: List[object]):
        self.domains = domains
        self.updated_at = datetime.utcnow()

    def get_dns_challenge(self) -> bool:
        return self.dns_challenge

    def set_dns_challenge(self, dns_challenge: bool):
        self.dns_challenge = dns_challenge
        self.updated_at = datetime.utcnow()

    def get_dns_config(self) -> Optional[object]:
        return self.dns_config

    def set_dns_config(self, dns_config: Optional[object]):
        self.dns_config = dns_config
        self.updated_at = datetime.utcnow()

    def get_certificate_path(self) -> Optional[str]:
        return self.certificate_path

    def set_certificate_path(self, certificate_path: Optional[str]):
        self.certificate_path = certificate_path
        self.updated_at = datetime.utcnow()

    def get_private_key_path(self) -> Optional[str]:
        return self.private_key_path

    def set_private_key_path(self, private_key_path: Optional[str]):
        self.private_key_path = private_key_path
        self.updated_at = datetime.utcnow()

    @classmethod
    def get_by_email(cls, items, email):
        """
        Specific method to get certificates by email.
        """
        return cls.get_by(items, 'email', email)

app/controllers/certificate_controller.py
from flask import Blueprint, render_template, request, redirect, url_for

from models.certificate import Certificate
from services.cert_manager import CertManager  # Assuming you'll have a CertManager
from utility import db, logger  # Usa il database manager globale

cert_manager = CertManager()  # Initialize CertManager

class CertificateController:
    """
    Controller for managing certificates.
    This controller handles the creation, retrieval, updating, and deletion of certificates.
    It interacts with the database manager and the certificate manager to perform these operations.
    """    
    def create_certificate(certificate_data: dict):
        """
        Creates a new certificate and saves it to the database.
        """
        try:
            certificate = Certificate(**certificate_data)
            
            db.create("certificates", certificate)

            # Generate the certificate using CertManager
            #cert_manager.generate_certificate(certificate)

            return True
        except Exception as e:
            raise e

    def get_certificate(certificate_id: str):
        """
        Retrieves a certificate from the database.
        """
        return db.get("certificates", certificate_id)

    def update_certificate(certificate_id: str, certificate_data: dict):
        """
        Updates an existing certificate in the database.
        """
        try:
            certificate = Certificate(**certificate_data)
            db.update("certificates", certificate_id, certificate)
            return certificate
        except Exception as e:
            raise e

    def delete_certificate(certificate_id: str):
        """
        Deletes a certificate from the database.
        """
        db.delete("certificates", certificate_id)


#region View Functions

    def list_view():
        """
        Renders the list view of certificates.
        """
        logger.info("Rendering certificate list view")
        certificates = db.list("certificates")
        domains = db.list("domains")

        return render_template('components/certificate/list.html', certificates=certificates, domains=domains)
    
    @classmethod
    def create_view(cls, request):
        """
        Renders the create certificate view.
        """
        if request.method == 'POST':

            try:
                logger.info("Creating certificate")

                certificate_data = request.form.to_dict() 
                certificate_data["dns_challenge"] = bool(certificate_data["dns_challenge"])           

                cls.create_certificate(certificate_data)
                return redirect(url_for('certificate.list'))
            except Exception as e:
                return render_template('components/certificate/create.html', errors=[str(e)])
            
        logger.info("Rendering create certificate view")
        domains = db.list("domains")
        return render_template('components/certificate/create.html', domains = domains, errors=None)
    
    def edit_view(certificate_id: str):
        """
        Renders the edit view for a specific certificate.
        """
        certificate = db.get("certificates", certificate_id)
        domains = db.list("domains")
        return render_template('components/certificate/edit.html', certificate=certificate, domains=domains)
    
    def delete_view(request: str):   
        """
        Deletes a certificate and redirects to the list view.
        """
        #get the certificate id from the request
        certificate_id = request.args.get("id")

        identifier = {"id": certificate_id}
        db.delete("certificates", identifier)
        return redirect(url_for('certificate.list'))
    
#endregion

app/routes/certificate.py
from flask import Blueprint, render_template, request, redirect, url_for
from controllers.certificate_controller import CertificateController

bp = Blueprint('certificate', __name__, url_prefix='/certificate')

@bp.route('/')
def list():
    return CertificateController.list_view()

@bp.route('/create', methods=['GET', 'POST'])
def create():
    return CertificateController.create_view(request)

@bp.route('/edit', methods=['GET', 'POST'])
def edit():
    return CertificateController.edit_view(request)

@bp.route('/delete', methods=['GET', 'POST'])
def delete():
    return CertificateController.delete_view(request)

app/templates/components/certificate/create.html
{% extends 'layouts/app-layout.html' %}

{% block content %}
  <h1>Create Certificate</h1>
  <form id="certificate_form" method="POST" action="{{ url_for('certificate.create') }}">
    <div class="form-group">
      <label for="name">Certificate Name</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="Enter certificate name" required>
    </div>

    <div class="form-group">
      <label for="type">Email</label>
      <input type="email" class="form-control" id="email" name="email" placeholder="Enter email address" required>
    </div>

    <div class="form-group">
      <label for="domain_id">Domain</label>
      <select class="form-control" id="domain_id" name="domains" required>
        {% for domain in domains %}
          <option value="{{ domain.id }}">{{ domain.name }}</option>
        {% endfor %}
      </select>
    </div>

    <label for="dns_challenge">DNS Challenge</label>
    <input type="checkbox" id="dns_challenge" name="dns_challenge" value="True">
    <input type="hidden" id="dns_challenge_hidden" name="dns_challenge">

    
    <label for="agree">Agree to Terms</label>
    <input type="checkbox" id="agree" required>
    
    <br>
    <br>
    <button type="submit" class="btn btn-primary">Create Certificate</button>
  </form>
{% endblock %}

{% block scripts %}
  <script>
    const form = document.getElementById('certificate_form');
    const checkbox = document.getElementById('dns_challenge');
    const hidden = document.getElementById('dns_challenge_hidden');

    form.addEventListener('submit', () => {
      hidden.value = checkbox.checked ? 'True' : 'False';
    });
  </script>
{% endblock %}

app/templates/components/certificate/list.html
{% extends 'layouts/app-layout.html' %}

{% block content %}
  <h1>Certificates</h1>
  <a href="{{ url_for('certificate.create') }}" class="btn btn-primary">Add New Certificate</a>

  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Certificate Name</th>
        <th>Email</th>
        <th>DNS Challenge</th>
        <th>Domain</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% for certificate in certificates %}
        <tr>
          <td>{{ certificate.id }}</td>
          <td>{{ certificate.name }}</td>
          <td>{{ certificate.email }}</td>
          <td>
            {% if certificate.dns_challenge %}
              <i class="fas fa-check"></i>
            {% else %}
              <i class="fas fa-times"></i>
            {% endif %}
            <td>
            {% for domain in domains %}
              {% if domain.id in certificate.domains %}
                {{ domain.name }}
              {% endif %}
            {% endfor %}
            </td>
          <td>
            <a href="{{ url_for('certificate.edit', id=certificate.id) }}" class="btn btn-sm btn-primary">Edit</a>
            <a href="{{ url_for('certificate.delete', id=certificate.id) }}" class="btn btn-sm btn-danger">Delete</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}